apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.global.awsAccountId }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: DB_HOST
          value: "{{ .Release.Name }}-postgres"
        - name: DB_NAME
          value: {{ .Values.postgres.dbName | quote }}
        - name: DB_USER
          value: {{ .Values.postgres.user | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: DB_PORT
          value: {{ .Values.postgres.port | quote }}
